server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    include: native
  cloud:
    config:
      server:
        native:
          search-locations: file://C:\FER\RASSUS\lab3\microservices\config-server-microservice\src\main\resources\
